version: "3.9"

services:
  php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
        args:
          TIMEZONE: ${TIMEZONE}
      restart: unless-stopped
      volumes:
        - php_socket:/var/run/php
        - ./:/var/www/symfony
      networks:
        - sf-skills-network
      container_name: sf_skills_php
      depends_on:
         - mysql
  mysql:
      image: mysql:8.0
      ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
      volumes:
        - ./.mysql:/var/lib/mysql
      networks:
        - sf-skills-network
      container_name: sf_skills_mysql

  nginx:
      image: nginx:stable-alpine
      volumes:
        - ./:/var/www/symfony
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - ${HTTP_PORT:-80}:80
      networks:
        - sf-skills-network
      container_name: sf_skills_nginx
      restart: unless-stopped
      env_file:
        - ./docker/nginx/.env.nginx
      depends_on:
        - php
        - mysql

  composer:
      image: composer:latest
      container_name: composer
      volumes:
        - ./:/var/www/symfony
      working_dir: /var/www/symfony
      networks:
        - sf-skills-network

volumes:
  php_socket:

networks:
    sf-skills-network:
        driver: bridge
