# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
        route: project_index
        permanent: true
        keepQueryParams: true
